spring:
  application:
    name: mall-member
  datasource:
    #MySQL配置
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://rm-2ze7pi8xlmr7ic1amqo.mysql.rds.aliyuncs.com/mall_ums?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: Czc193590
  cloud:
    nacos:
      discovery:
        #Nacos Server address
        server-addr: 8.136.7.205:8848

mybatis-plus:
  mapper-location: classpath:mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto

server:
  port: 8000
