spring:
  datasource:
    #MySQL配置
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://rm-2ze7pi8xlmr7ic1amqo.mysql.rds.aliyuncs.com/mall_wms?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: Czc193590
  cloud:
    nacos:
      discovery:
        server-addr: 8.136.7.205:8848
  application:
    name: mall-ware
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis-plus:
  mapper-location: classpath:mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto

server:
  port: 11000
